# Site settings
title: Solace Messaging using Node.js over AMQP
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-amqp-nodejs"
repository: https://github.com/SolaceSamples/solace-samples-amqp-nodejs

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-get-started-amqp: //dev.solace.com/get-started/amqp-tutorials/
links-get-started-java-topic-to-queue-mapping: //dev.solace.com/get-started/java-tutorials/topic-queue-mapping_java/
links-get-started-jms-topic-to-queue-mapping: //dev.solace.com/get-started/jms-tutorials/topic-queue-mapping_jms/
links-community: //solace.com/support/
links-downloads: //solace.com/downloads/
links-tech-other: //solace.com/products/tech/
links-solaceCloud-setup: //solace.com/cloud/
docs-core-concepts: //docs.solace.com/PubSub-Basics/Core-Concepts.htm
docs-management-tools: //docs.solace.com/Management-Tools.htm
docs-management-soladmin: //docs.solace.com/SolAdmin/SolAdmin-Overview.htm?Highlight=SolAdmin
docs-management-cli: //docs.solace.com/Solace-CLI/Using-Solace-CLI.htm
docs-topic-mapping: //docs.solace.com/PubSub-Basics/Core-Concepts.htm
docs-semp: //docs.solace.com/SEMP/Using-SEMP-to-Manage-and-Monitor-Routers.htm
docs-semp-get-started: //docs.solace.com/SEMP/SEMP-Get-Started.htm
docs-configure-queues: //https://docs.solace.com/Configuring-and-Managing/Configuring-Queues.htm
