# Site settings
title: Solace Messaging using Node.js over AMQP
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-amqp-nodejs"
repository: https://github.com/SolaceSamples/solace-samples-amqp-nodejs

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-get-started-amqp: http://dev.solace.com/get-started/amqp-tutorials/
links-get-started-java-topic-to-queue-mapping: http://dev.solace.com/get-started/java-tutorials/topic-queue-mapping_java/
links-get-started-jms-topic-to-queue-mapping: http://dev.solace.com/get-started/jms-tutorials/topic-queue-mapping_jms/
links-community: http://dev.solace.com/community/
links-downloads: http://dev.solace.com/downloads/
links-tech-other: http://dev.solace.com/tech/#other
links-solaceCloud-setup: http://cloud.solace.com/create-messaging-service/
docs-core-concepts: http://docs.solace.com/Features/Core-Concepts.htm
docs-management-tools: http://docs.solace.com/Management-Tools.htm
docs-management-soladmin: http://docs.solace.com/SolAdmin/SolAdmin-Home.htm?Highlight=SolAdmin
docs-management-cli: http://docs.solace.com/Configuring-and-Managing-Routers/Using-the-Solace-Router-CLI.htm
docs-topic-mapping: http://docs.solace.com/Features/Core-Concepts.htm#topic-queue-mapping
docs-semp: http://docs.solace.com/SEMP/Using-SEMP-to-Manage-and-Monitor-Routers.htm
docs-semp-get-started: http://docs.solace.com/SEMP/SEMP-Get-Started.htm
docs-configure-queues: http://docs.solace.com/Configuring-and-Managing-Routers/Configuring-Queues.htm
docs-vmr-setup: http://docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
solace-apis-dev:
  - value: http://dev.solace.com/get-started/c-tutorials/
    name: C
  - value: http://dev.solace.com/get-started/dotnet-tutorials/
    name: C#/.NET
  - value: http://dev.solace.com/get-started/java-tutorials/
    name: Java
  - value: http://dev.solace.com/get-started/java-rto-tutorials/
    name: Java RTO
  - value: http://dev.solace.com/get-started/javascript-tutorials/
    name: JavaScript
  - value: http://dev.solace.com/get-started/node-js-tutorials/
    name: Node.js
open-apis-dev:
  - value: http://dev.solace.com/get-started/amqp-tutorials-jms-11/
    name: AMQP - JMS 1.1
  - value: http://dev.solace.com/get-started/amqp-tutorials-jms-2/
    name: AMQP - JMS 2.0
  - value: http://dev.solace.com/get-started/amqp-tutorials-node-js/
    name: AMQP - Node.js
  - value: http://dev.solace.com/get-started/mqtt-tutorials/
    name: MQTT - Eclipse Paho Java
  - value: http://dev.solace.com/get-started/amqp-tutorials-jms-11/
    name: JMS 1.1 - Apache Qpid
  - value: http://dev.solace.com/get-started/amqp-tutorials-jms-2/
    name: JMS 2.0 - Apache Qpid
  - value: http://dev.solace.com/get-started/jms-tutorials/
    name: JMS 1.1 - Solace
  - value: http://dev.solace.com/get-started/openmama-tutorials/
    name: OpenMAMA
  - value: http://dev.solace.com/get-started/rest-tutorials/
    name: REST Messaging
other-environments-dev:
  - value: http://dev.solace.com/get-started/pcf-tutorials/
    name: Pivotal Cloud Foundry


#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
