# Site settings
title: Solace Messaging using Node.js over AMQP
baseurl: "/solace-samples-amqp-nodejs"
repository: https://github.com/SolaceSamples/solace-samples-amqp-nodejs

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-get-started-amqp: http://dev.solace.com/get-started/amqp-tutorials/
links-get-started-java-topic-to-queue-mapping: http://dev.solace.com/get-started/java-tutorials/topic-queue-mapping_java/
links-get-started-jms-topic-to-queue-mapping: http://dev.solace.com/get-started/jms-tutorials/topic-queue-mapping_jms/
links-community: http://dev.solace.com/community/
links-downloads: http://dev.solace.com/downloads/
links-tech-other: http://dev.solace.com/tech/#other
docs-vmr-setup: http://docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
docs-core-concepts: http://docs.solace.com/Features/Core-Concepts.htm
docs-management-tools: http://docs.solace.com/Management-Tools.htm
docs-management-soladmin: http://docs.solace.com/SolAdmin/SolAdmin-Home.htm?Highlight=SolAdmin
docs-management-cli: http://docs.solace.com/Configuring-and-Managing-Routers/Using-the-Solace-Router-CLI.htm
docs-topic-mapping: http://docs.solace.com/Features/Core-Concepts.htm#topic-queue-mapping
docs-semp: http://docs.solace.com/SEMP/Using-SEMP-to-Manage-and-Monitor-Routers.htm
docs-semp-get-started: http://docs.solace.com/SEMP/SEMP-Get-Started.htm
docs-confugure-queues: http://docs.solace.com/Configuring-and-Managing-Routers/Configuring-Queues.htm


#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
